export const metadata = {
  title: 'Color Harmony Generator & Wheel - Create Beautiful Color Schemes',
  description: 'Free online color harmony generator and wheel tool. Create harmonious color schemes with complementary, triadic, analogous, split-complementary, and monochromatic color relationships. Perfect for designers, artists and web developers.',
  keywords: [
    'color harmony',
    'color harmony wheel',
    'color harmony generator',
    'color harmony examples',
    'color harmony palette',
    'color harmony definition',
    'color harmony meaning',
    'color harmony app',
    'color harmony tool',
    'color wheel generator',
    'color scheme',
    'color palette creator',
    'complementary colors',
    'triadic colors',
    'analogous colors',
    'split-complementary',
    'monochromatic',
    'color theory tool',
    'design color palette',
    'web design colors',
    'UI color scheme',
    'harmonious color combinations',
    'color matching tool',
    'best color combinations',
    'professional color schemes',
    'color harmony for web design',
    'color harmony for drawing',
    'color wheel theory',
  ],
  alternates: {
    canonical: 'https://rgbatohex.com/tools/color-harmony',
  },
  openGraph: {
    title: 'Color Harmony Wheel & Generator - Create Professional Color Schemes',
    description: 'Free online color harmony wheel and generator. Create perfectly harmonious color schemes and palettes with complementary, triadic, analogous, and other color harmony types. View examples and export to CSS, Sass, or JSON.',
    url: 'https://rgbatohex.com/tools/color-harmony',
    type: 'website',
    siteName: 'RGBA to HEX',
  },
}; 