import { GreenShadeCategory, GreenCategory } from '../types/greenShades';

// 绿色系分类定义
export const GREEN_SHADE_CATEGORIES: GreenShadeCategory[] = [
  {
    id: GreenCategory.LIGHT_GREEN,
    name: 'light-green',
    displayName: 'Light Green',
    hueRange: [80, 150],
    saturationRange: [30, 80],
    lightnessRange: [70, 95],
    color: '#90EE90',
    description: 'Soft, calming light green shades perfect for peaceful designs',
    examples: ['Light Green', 'Pale Green', 'Mint Cream', 'Honeydew'],
    seoKeywords: ['light green', 'pale green', 'soft green', 'mint green'],
    psychologyEffect: 'Calming, refreshing, natural, peaceful',
    designUsage: ['Backgrounds', 'Wellness brands', 'Nature products', 'Healthcare'],
  },
  {
    id: GreenCategory.MEDIUM_GREEN,
    name: 'medium-green',
    displayName: 'Medium Green',
    hueRange: [100, 140],
    saturationRange: [50, 90],
    lightnessRange: [40, 70],
    color: '#32CD32',
    description: 'Balanced green tones that work well in most design contexts',
    examples: ['Lime Green', 'Forest Green', 'Green', 'Spring Green'],
    seoKeywords: ['medium green', 'lime green', 'classic green', 'standard green'],
    psychologyEffect: 'Natural, balanced, growth, harmony',
    designUsage: ['Environmental brands', 'Technology', 'Outdoor products', 'Health & fitness'],
  },
  {
    id: GreenCategory.DARK_GREEN,
    name: 'dark-green',
    displayName: 'Dark Green',
    hueRange: [100, 140],
    saturationRange: [60, 100],
    lightnessRange: [10, 40],
    color: '#006400',
    description: 'Deep, sophisticated dark green shades for elegant designs',
    examples: ['Dark Green', 'Forest Green', 'Hunter Green', 'Pine Green'],
    seoKeywords: ['dark green', 'forest green', 'deep green', 'hunter green'],
    psychologyEffect: 'Sophisticated, stable, trustworthy, professional',
    designUsage: ['Luxury brands', 'Financial services', 'Traditional brands', 'Formal wear'],
  },
  {
    id: GreenCategory.FOREST_GREEN,
    name: 'forest-green',
    displayName: 'Forest Green',
    hueRange: [110, 130],
    saturationRange: [70, 100],
    lightnessRange: [20, 50],
    color: '#228B22',
    description: 'Natural forest-inspired green shades that evoke nature and growth',
    examples: ['Forest Green', 'Pine Green', 'Jungle Green', 'Evergreen'],
    seoKeywords: ['forest green', 'pine green', 'nature green', 'woodland green'],
    psychologyEffect: 'Natural, grounded, stable, organic',
    designUsage: ['Outdoor brands', 'Environmental organizations', 'Natural products', 'Adventure gear'],
  },
  {
    id: GreenCategory.LIME_GREEN,
    name: 'lime-green',
    displayName: 'Lime Green',
    hueRange: [70, 100],
    saturationRange: [60, 100],
    lightnessRange: [50, 80],
    color: '#32CD32',
    description: 'Vibrant lime green shades that combine energy with natural appeal',
    examples: ['Lime Green', 'Chartreuse', 'Yellow Green', 'Lawn Green'],
    seoKeywords: ['lime green', 'chartreuse', 'yellow green', 'bright green'],
    psychologyEffect: 'Energetic, fresh, vibrant, youthful',
    designUsage: ['Sports brands', 'Energy drinks', 'Youth products', 'Modern tech'],
  },
  {
    id: GreenCategory.EMERALD_GREEN,
    name: 'emerald-green',
    displayName: 'Emerald Green',
    hueRange: [120, 140],
    saturationRange: [70, 100],
    lightnessRange: [30, 60],
    color: '#50C878',
    description: 'Precious emerald green shades that convey luxury and elegance',
    examples: ['Emerald', 'Jade Green', 'Malachite', 'Sea Green'],
    seoKeywords: ['emerald green', 'jade green', 'precious green', 'luxury green'],
    psychologyEffect: 'Luxurious, precious, sophisticated, valuable',
    designUsage: ['Luxury brands', 'Jewelry', 'High-end products', 'Premium services'],
  },
  {
    id: GreenCategory.MINT_GREEN,
    name: 'mint-green',
    displayName: 'Mint Green',
    hueRange: [140, 170],
    saturationRange: [40, 80],
    lightnessRange: [60, 90],
    color: '#98FB98',
    description: 'Fresh mint green shades that blend green with subtle blue undertones',
    examples: ['Mint Green', 'Aquamarine', 'Turquoise Green', 'Seafoam'],
    seoKeywords: ['mint green', 'seafoam green', 'aqua green', 'fresh green'],
    psychologyEffect: 'Fresh, clean, cooling, refreshing',
    designUsage: ['Beauty products', 'Spa & wellness', 'Fresh brands', 'Summer collections'],
  },
  {
    id: GreenCategory.OLIVE_GREEN,
    name: 'olive-green',
    displayName: 'Olive Green',
    hueRange: [60, 90],
    saturationRange: [30, 70],
    lightnessRange: [30, 60],
    color: '#808000',
    description: 'Earthy olive green shades with yellow undertones for natural designs',
    examples: ['Olive', 'Olive Drab', 'Khaki Green', 'Army Green'],
    seoKeywords: ['olive green', 'army green', 'military green', 'earthy green'],
    psychologyEffect: 'Earthy, natural, military, practical',
    designUsage: ['Military', 'Outdoor gear', 'Vintage designs', 'Earthy brands'],
  },
];

// 获取绿色分类的辅助函数
export function getGreenCategoryById(id: string): GreenShadeCategory | undefined {
  return GREEN_SHADE_CATEGORIES.find(category => category.id === id);
}

export function getGreenCategoriesByHue(hue: number): GreenShadeCategory[] {
  return GREEN_SHADE_CATEGORIES.filter(category => {
    const [min, max] = category.hueRange;
    return hue >= min && hue <= max;
  });
}

// SEO相关的绿色关键词
export const GREEN_SEO_KEYWORDS = [
  'shades of green',
  'green color palette',
  'green hex codes',
  'green color names',
  'different shades of green',
  'green color chart',
  'forest green shades',
  'light green colors',
  'dark green shades',
  'lime green variations',
  'mint green colors',
  'emerald green palette',
  'green color code',
  'green colour shades',
  'shade of green',
  'types of green',
  'green color shades',
  'shades of green color',
  'green hex code',
  'all shades of green',
  'green shade',
  'types of green colors',
  'green colour',
  'green css',
  'green gradient',
];
