import { OrangeShadeCategory, OrangeCategory } from '../types/orangeShades';

// 橙色系分类定义
export const ORANGE_SHADE_CATEGORIES: OrangeShadeCategory[] = [
  {
    id: OrangeCategory.LIGHT_ORANGE,
    name: 'light-orange',
    displayName: 'Light Orange',
    hueRange: [15, 35],
    saturationRange: [30, 80],
    lightnessRange: [80, 95],
    color: '#FFE4B5',
    description: 'Soft, gentle light orange shades perfect for warm and cheerful designs',
    examples: ['Light Orange', 'Pale Orange', 'Peach Puff', 'Papaya Whip'],
    seoKeywords: ['light orange', 'pale orange', 'soft orange', 'peach orange', 'cream orange'],
    psychologyEffect: 'Gentle, warm, cheerful, comforting',
    designUsage: ['Baby products', 'Autumn themes', 'Warm brands', 'Soft backgrounds'],
  },
  {
    id: OrangeCategory.MEDIUM_ORANGE,
    name: 'medium-orange',
    displayName: 'Medium Orange',
    hueRange: [20, 30],
    saturationRange: [70, 95],
    lightnessRange: [50, 80],
    color: '#FFA500',
    description: 'Classic orange tones that represent energy and enthusiasm',
    examples: ['Orange', 'Dark Orange', 'Orange Red', 'Tangerine'],
    seoKeywords: ['medium orange', 'classic orange', 'true orange', 'bright orange'],
    psychologyEffect: 'Energetic, enthusiastic, vibrant, attention-grabbing',
    designUsage: ['Brand logos', 'Call-to-action buttons', 'Sports themes', 'Energy products'],
  },
  {
    id: OrangeCategory.DARK_ORANGE,
    name: 'dark-orange',
    displayName: 'Dark Orange',
    hueRange: [15, 25],
    saturationRange: [60, 100],
    lightnessRange: [20, 50],
    color: '#FF8C00',
    description: 'Deep, rich dark orange shades for sophisticated and bold designs',
    examples: ['Dark Orange', 'Burnt Orange', 'Rust Orange', 'Copper Orange'],
    seoKeywords: ['dark orange', 'deep orange', 'burnt orange', 'rust orange'],
    psychologyEffect: 'Bold, sophisticated, earthy, powerful',
    designUsage: ['Luxury brands', 'Autumn themes', 'Industrial designs', 'Corporate identity'],
  },
  {
    id: OrangeCategory.RED_ORANGE,
    name: 'red-orange',
    displayName: 'Red Orange',
    hueRange: [10, 20],
    saturationRange: [70, 100],
    lightnessRange: [40, 70],
    color: '#FF4500',
    description: 'Vibrant red-orange shades that combine passion with energy',
    examples: ['Red Orange', 'Orange Red', 'Vermillion', 'Scarlet Orange'],
    seoKeywords: ['red orange', 'orange red', 'vermillion orange', 'scarlet orange'],
    psychologyEffect: 'Passionate, energetic, bold, exciting',
    designUsage: ['Sports brands', 'Warning signs', 'Action themes', 'Dynamic designs'],
  },
  {
    id: OrangeCategory.YELLOW_ORANGE,
    name: 'yellow-orange',
    displayName: 'Yellow Orange',
    hueRange: [35, 45],
    saturationRange: [80, 100],
    lightnessRange: [60, 85],
    color: '#FFAE42',
    description: 'Bright yellow-orange shades with sunny, optimistic appeal',
    examples: ['Yellow Orange', 'Amber', 'Marigold', 'Saffron'],
    seoKeywords: ['yellow orange', 'amber orange', 'marigold orange', 'saffron orange'],
    psychologyEffect: 'Optimistic, sunny, cheerful, uplifting',
    designUsage: ['Food brands', 'Summer themes', 'Children products', 'Happy designs'],
  },
  {
    id: OrangeCategory.PEACH_ORANGE,
    name: 'peach-orange',
    displayName: 'Peach Orange',
    hueRange: [20, 35],
    saturationRange: [40, 80],
    lightnessRange: [75, 90],
    color: '#FFCBA4',
    description: 'Soft peach orange shades that blend orange with gentle pink undertones',
    examples: ['Peach', 'Coral', 'Salmon', 'Apricot'],
    seoKeywords: ['peach orange', 'coral orange', 'salmon orange', 'apricot orange'],
    psychologyEffect: 'Gentle, romantic, soft, nurturing',
    designUsage: ['Beauty brands', 'Wedding themes', 'Feminine designs', 'Wellness products'],
  },
];

// 获取橙色分类的辅助函数
export function getOrangeCategoryById(id: string): OrangeShadeCategory | undefined {
  return ORANGE_SHADE_CATEGORIES.find(category => category.id === id);
}

export function getOrangeCategoriesByHue(hue: number): OrangeShadeCategory[] {
  return ORANGE_SHADE_CATEGORIES.filter(category => {
    const [min, max] = category.hueRange;
    return hue >= min && hue <= max;
  });
}

// SEO相关的橙色关键词
export const ORANGE_SEO_KEYWORDS = [
  'shades of orange',
  'shades of orange color palette',
  'shades of orange hex codes',
  'shades of orange color names',
  'different shades of orange',
  'shades of orange color chart',
  'dark shades of orange',
  'light shades of orange',
  'red shades of orange',
  'yellow shades of orange variations',
  'peach shades of orange',
  'shades of orange color combination',
  'shades of orange color gradient',
  'types of shades of orange',
  'shades of orange color scheme',
  'soft shades of orange',
  'shades of orange color all shades',
  'orange color code',
  'orange colors',
  'orange shades',
  'orange color shades',
  'orange color',
  'hex code orange',
  'shades of color',
  'color orange',
  'orange color code',
  'color orange shades',
  'all shades of orange',
  'best shades of orange',
  'popular shades of orange',
  'beautiful shades of orange',
  'color shades palette',
  'color shades collection',
  'color shades combinations',
  'color shades gradients',
  'light color shades',
  'dark color shades',
  'vibrant color shades',
  'soft color shades',
];
