import { PurpleShadeCategory, PurpleCategory } from '../types/purpleShades';

// 紫色系分类定义
export const PURPLE_SHADE_CATEGORIES: PurpleShadeCategory[] = [
  {
    id: PurpleCategory.LIGHT_PURPLE,
    name: 'light-purple',
    displayName: 'Light Purple',
    hueRange: [270, 300],
    saturationRange: [30, 70],
    lightnessRange: [70, 95],
    color: '#DDA0DD',
    description: 'Soft, calming light purple shades perfect for gentle and peaceful designs',
    examples: ['Light Purple', 'Pale Purple', 'Soft Purple', 'Baby Purple'],
    seoKeywords: ['light purple', 'pale purple', 'soft purple', 'pastel purple'],
    psychologyEffect: 'Calming, gentle, romantic, dreamy',
    designUsage: ['Beauty products', 'Baby brands', 'Wellness', 'Feminine designs'],
  },
  {
    id: PurpleCategory.DEEP_PURPLE,
    name: 'deep-purple',
    displayName: 'Deep Purple',
    hueRange: [260, 280],
    saturationRange: [60, 100],
    lightnessRange: [10, 40],
    color: '#483D8B',
    description: 'Rich, sophisticated deep purple shades that convey luxury and mystery',
    examples: ['Deep Purple', 'Dark Purple', 'Midnight Purple', 'Shadow Purple'],
    seoKeywords: ['deep purple', 'dark purple', 'shades of deep purple', 'midnight purple'],
    psychologyEffect: 'Mysterious, sophisticated, powerful, luxurious',
    designUsage: ['Luxury brands', 'Premium products', 'Entertainment', 'High-end fashion'],
  },
  {
    id: PurpleCategory.LAVENDER_PURPLE,
    name: 'lavender-purple',
    displayName: 'Lavender Purple',
    hueRange: [280, 300],
    saturationRange: [40, 80],
    lightnessRange: [60, 90],
    color: '#E6E6FA',
    description: 'Delicate lavender purple shades inspired by the beautiful lavender flower',
    examples: ['Lavender', 'Lavender Blush', 'French Lavender', 'English Lavender'],
    seoKeywords: ['lavender purple', 'lavender color', 'lavender shades', 'floral purple'],
    psychologyEffect: 'Relaxing, therapeutic, natural, serene',
    designUsage: ['Spa & wellness', 'Aromatherapy', 'Natural products', 'Relaxation brands'],
  },
  {
    id: PurpleCategory.ROYAL_PURPLE,
    name: 'royal-purple',
    displayName: 'Royal Purple',
    hueRange: [270, 290],
    saturationRange: [70, 100],
    lightnessRange: [30, 60],
    color: '#7851A9',
    description: 'Majestic royal purple shades that embody nobility and grandeur',
    examples: ['Royal Purple', 'Imperial Purple', 'Regal Purple', 'Crown Purple'],
    seoKeywords: ['royal purple', 'imperial purple', 'regal purple', 'noble purple'],
    psychologyEffect: 'Noble, majestic, authoritative, prestigious',
    designUsage: ['Luxury brands', 'Premium services', 'Royal themes', 'High-end products'],
  },
  {
    id: PurpleCategory.VIOLET_PURPLE,
    name: 'violet-purple',
    displayName: 'Violet Purple',
    hueRange: [250, 270],
    saturationRange: [50, 90],
    lightnessRange: [40, 70],
    color: '#8A2BE2',
    description: 'Classic violet purple shades that balance blue and red undertones perfectly',
    examples: ['Violet', 'Blue Violet', 'Red Violet', 'Medium Violet'],
    seoKeywords: ['violet purple', 'violet color', 'blue violet', 'classic violet'],
    psychologyEffect: 'Creative, artistic, imaginative, inspiring',
    designUsage: ['Art & design', 'Creative industries', 'Education', 'Innovation brands'],
  },
  {
    id: PurpleCategory.MAGENTA_PURPLE,
    name: 'magenta-purple',
    displayName: 'Magenta Purple',
    hueRange: [290, 320],
    saturationRange: [60, 100],
    lightnessRange: [50, 80],
    color: '#FF00FF',
    description: 'Vibrant magenta purple shades that combine purple with pink energy',
    examples: ['Magenta', 'Fuchsia', 'Hot Pink Purple', 'Electric Purple'],
    seoKeywords: ['magenta purple', 'fuchsia purple', 'bright purple', 'electric purple'],
    psychologyEffect: 'Energetic, bold, confident, attention-grabbing',
    designUsage: ['Fashion', 'Entertainment', 'Youth brands', 'Bold designs'],
  },
  {
    id: PurpleCategory.PLUM_PURPLE,
    name: 'plum-purple',
    displayName: 'Plum Purple',
    hueRange: [280, 310],
    saturationRange: [40, 80],
    lightnessRange: [30, 60],
    color: '#8E4585',
    description: 'Rich plum purple shades inspired by the deep color of ripe plums',
    examples: ['Plum', 'Wine Purple', 'Burgundy Purple', 'Mulberry'],
    seoKeywords: ['plum purple', 'wine purple', 'burgundy purple', 'mulberry purple'],
    psychologyEffect: 'Sophisticated, mature, rich, elegant',
    designUsage: ['Wine & spirits', 'Gourmet food', 'Mature brands', 'Autumn themes'],
  },
  {
    id: PurpleCategory.AMETHYST_PURPLE,
    name: 'amethyst-purple',
    displayName: 'Amethyst Purple',
    hueRange: [260, 290],
    saturationRange: [50, 90],
    lightnessRange: [40, 70],
    color: '#9966CC',
    description: 'Precious amethyst purple shades that capture the beauty of the gemstone',
    examples: ['Amethyst', 'Crystal Purple', 'Gem Purple', 'Jewel Purple'],
    seoKeywords: ['amethyst purple', 'crystal purple', 'gem purple', 'precious purple'],
    psychologyEffect: 'Spiritual, mystical, precious, transformative',
    designUsage: ['Jewelry', 'Spiritual brands', 'Luxury goods', 'Mystical themes'],
  },
];

// 获取紫色分类的辅助函数
export function getPurpleCategoryById(id: string): PurpleShadeCategory | undefined {
  return PURPLE_SHADE_CATEGORIES.find(category => category.id === id);
}

export function getPurpleCategoriesByHue(hue: number): PurpleShadeCategory[] {
  return PURPLE_SHADE_CATEGORIES.filter(category => {
    const [min, max] = category.hueRange;
    return hue >= min && hue <= max;
  });
}

// SEO相关的紫色关键词
export const PURPLE_SEO_KEYWORDS = [
  'shades of purple',
  'purple color',
  'purple shades',
  'purple colors',
  'purple color code',
  'purple color shades',
  'purple gradient',
  'purple hex code',
  'purple color palette',
  'purple colours',
  'purple shade',
  'types of purple',
  'shades of purple names',
  'different shades of purple',
  'all shades of purple',
  'shades of deep purple',
  'light purple shades',
  'dark purple colors',
  'violet purple',
  'lavender purple',
  'royal purple',
  'magenta purple',
  'plum purple',
  'amethyst purple',
  'purple color chart',
  'purple hex codes',
  'purple color names',
  'purple css',
  'purple variations',
  'purple tones',
];
